name: Build and Add to Registry

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  AzureBicepDeploy:
    runs-on: ubuntu-latest
    env:
      ResourceGroupName: rg-myci-githubregistry
    steps:
      - uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDS }}

      - name: Build Bicep File
        run: |
          az bicep build --file infrastructure/azure.bicep

      - name: Create Resource Group
        uses: Azure/CLI@v1
        with:
          inlineScript: |
            az group create --name ${{ env.ResourceGroupName }} --location westeurope

      - name: Deploy Bicep File
        uses: Azure/arm-deploy@v1
        with:
          resourceGroupName: ${{ env.ResourceGroupName }}
          subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}
          template: infrastructure/azure.json

  BuildAndPush:
    runs-on: ubuntu-latest
    env:
      Configuration: Release
      Registry: ghcr.io
      Repository: ${{ github.repository }}

    steps:
      - uses: actions/checkout@v2

      - name: dotnet build
        run: dotnet build --configuration ${{ env.Configuration }}
        shell: pwsh

      - name: Login to the container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.Registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Docker meta (tags and labels)
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/johnlokerse/dotnethelloworld:latest

      - name: Install buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true

      - name: Build and push docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/johnlokerse/dotnethelloworld:latest
          labels: ${{ steps.meta.outputs.labels }}